Gemfile, Gemfile.lock, app/models/user.rb, config/initializers/devise.rb, config/locales/devise.en.yml, config/routes.rb, db/migrate/20230227140447_devise_create_users.rb, db/schema.rb, test/models/user_test.rb
Hi guys! could you please check the model?
=> user model created with devise

app/models/bar.rb, db/migrate/20230227141350_create_bars.rb, db/schema.rb, test/models/bar_test.rb
=> ajout du model des bars

app/models/bar.rb, config/routes.rb
=> Ajout des routes

app/models/bar.rb, app/models/event.rb, app/models/user.rb
I added relations and validation for models "event" & "bar". 
Je ne l'ai pas fait pour users car il manque des champs au model (style de musique, etc.)
=> relations and validates for models event & bar

app/controllers/events_controller.rb, test/controllers/events_controller_test.rb
création des controller et des méthodes rattachée à event
=> création du controller event

app/controllers/bars_controller.rb, app/models/bar.rb, app/views/bars/edit.html.erb, app/views/bars/index.html.erb, app/views/bars/new.html.erb, app/views/bars/show.html.erb, test/controllers/bars_controller_test.rb
dans un monde meilleur vous verriez des screens
=> Ai fini le bars controller hors photos

app/models/user.rb, db/migrate/20230227165816_add_details_to_users.rb, db/schema.rb
I added the details to the users (database and model) as well as the validations
=> model updates with details

app/controllers/application_controller.rb, app/controllers/pages_controller.rb, app/models/user.rb, app/views/shared/_navbar.html.erb
Now user can login logout and register
I had to removed validation usernam
=> User Login

.gitignore, Gemfile, Gemfile.lock, app/controllers/events_controller.rb, app/controllers/users_controller.rb, app/models/bar.rb, app/models/event.rb, app/models/user.rb, config/environments/development.rb, config/storage.yml, db/migrate/20230228101910_create_active_storage_tables.active_storage.rb, db/schema.rb
Mise en place de la gem cloudinary et du fichier .env ainsi que la maj des permits dans les controllers bars, users et events pour ajouter des photos.
Il faudra mettre les photos dans  formulaires dans les prochains tickets
=> Mep cloudinary

app/controllers/bars_controller.rb, app/models/bar.rb, app/views/bars/index.html.erb, config/routes.rb, db/seeds.rb
J'ai ajouté le controller des bars
=> Fix bars controller

app/controllers/bars_controller.rb, app/policies/bar_policy.rb, config/routes.rb
I updated:
- the bar policy
- the bars controller
=> destroy method for bars

app/controllers/events_controller.rb, app/policies/event_policy.rb, app/views/bars/show.html.erb, test/policies/event_policy_test.rb
Mise à jour du pundit et policies pour les events.
Seul l'owner de l'event peut le destroy, les user peuvent l'edit
=> pundit pour les events

app/models/bar.rb, app/views/bars/edit.html.erb, app/views/bars/new.html.erb
just added the field "location" (adresse) pour les views "new" et "edit" de bars
=> added location to the form bar

app/controllers/application_controller.rb, app/controllers/bars_controller.rb, app/views/bars/mybars.html.erb, app/views/pages/home.html.erb, config/routes.rb
création de la route mybars
création de la method my bars
création de la vue mybars 
je ne vois que mes bars
=> lister les bars dans une vue mybars

app/views/bars/mybars.html.erb
Lot of change in the mybars view
=> A bar can manage it's events

app/views/bars/show.html.erb
=> added the destroy authorization bar only for owners

app/assets/stylesheets/application.scss, app/assets/stylesheets/components/_home_button.scss, app/assets/stylesheets/pages/_banner.scss, app/assets/stylesheets/pages/_home.scss, app/views/pages/home.html copy.erb, app/views/pages/home.html.erb
C'est mobile friendly, c'est trop cool.
=> ajout de boutons sous la banner

app/assets/stylesheets/application.scss, app/assets/stylesheets/components/_bar_banner.scss, app/views/bars/show.html.erb
J'ai changé la position et la forme des boutons edit et delete de la show, ainsi que la disposition des infos du bar
=> modifications de la show

Gemfile, Gemfile.lock, app/assets/stylesheets/components/_address_autocomplete.scss, app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/components/_map.scss, app/controllers/bars_controller.rb, app/javascript/controllers/address_autocomplete_controller.js, app/javascript/controllers/index.js, app/javascript/controllers/map_controller.js, app/models/bar.rb, app/views/bars/_info_window.html.erb, app/views/bars/_marker.html.erb, app/views/bars/edit.html.erb, app/views/bars/index.html.erb, app/views/bars/new.html.erb, app/views/layouts/application.html.erb, config/initializers/geocoder.rb, db/migrate/20230301135503_add_coordinates_to_bars.rb, db/schema.rb, package.json, yarn.lock
Mise en place de geocoder : 
Problème avec le design du champ auto complete
il faudra faire une partial avec le formulaire pour new et edit
=> v1 de geocoder

app/policies/event_policy.rb, app/views/bars/show.html.erb
fix sur l'edit event pour tout le monde
mise en place de la navbar sur le show d'un bar
=> fix edit event conflict navbar show bar

app/assets/stylesheets/application.scss, app/assets/stylesheets/components/_footer.scss, app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/config/_colors.scss, app/views/layouts/application.html.erb, app/views/pages/home.html.erb, app/views/shared/_footer.html.erb
le footer a été mis sur toutes les pages (dans application.html.erb) mais il s'affiche bizarrement sur la page du login et je ne sais pas comment résoudre ce problème..
=> footer implemented

app/assets/stylesheets/application.scss, app/javascript/controllers/flatpicker_controller.js, app/javascript/controllers/flatpickr_controller.js, app/javascript/controllers/index.js, app/views/events/new.html.erb, app/views/layouts/application.html.erb, package.json, yarn.lock
J'ai enfin réussi à créer le calendar de Flatpickr!
=> 60 as a user i want to select my event date on a calendar using flatpickr

app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/components/_row_new_event.scss, app/controllers/bars_controller.rb, app/views/bars/show.html.erb
=> show bar changed including the event form

app/assets/stylesheets/components/_card.scss, app/assets/stylesheets/components/_footer.scss, app/assets/stylesheets/components/_navbar.scss, app/assets/stylesheets/config/_links.scss, app/assets/stylesheets/pages/_banner.scss, app/assets/stylesheets/pages/_home.scss, app/controllers/pages_controller.rb, app/views/layouts/application.html.erb, app/views/pages/home.html.erb, app/views/shared/_navbar.html.erb, app/views/shared/_navbarmusician.html.erb, app/views/shared/_navbarowner.html.erb
mise en place du style de la front page 
mise en place du style de la nav bar de la home
=> Front home page

app/assets/stylesheets/components/_event_dashboard.scss, app/views/bars/_barlist.html.erb, app/views/bars/_mybarsevents.html.erb, app/views/bars/mybars.html.erb
il faudra résoudre d'autres soucis de display
=> fixed part of the display

app/assets/stylesheets/config/_bootstrap_variables.scss, app/assets/stylesheets/pages/_barshow.scss, app/assets/stylesheets/pages/_index.scss, app/controllers/bars_controller.rb, app/views/bars/show.html.erb
mise en page du show du bar avec ajout des events du bar
=> Show du bar front
